/**
 * Auto generated from rule/Final.lpx
 * DO NOT EDIT THIS FILE MANUALLY
 */

// Bettbox compatibility
const Compatible_With_Bettbox = {
  ruleOptionsEnable: true,
};

const customRules = [
  'DOMAIN-SUFFIX,itdog.cn,DIRECT',
  'DOMAIN-SUFFIX,tianliyun.cn,兜底分流',
  'DOMAIN-SUFFIX,andnode.com,兜底分流',
  'DOMAIN-SUFFIX,sadidc.com,兜底分流',
  'DOMAIN-SUFFIX,19966998.xyz,兜底分流',
  'DOMAIN,hinet.lazycat.cv,DIRECT',
  'DOMAIN-SUFFIX,jtti.cc,兜底分流',
  'DOMAIN-SUFFIX,acgf.vip,兜底分流',
  'DOMAIN-SUFFIX,tyyunidc.cn,兜底分流',
  'DOMAIN-SUFFIX,matrixidc.net,兜底分流',
  'DOMAIN-SUFFIX,antping.com,兜底分流',
  'DOMAIN-SUFFIX,myip.ipip.net,DIRECT',
  'DOMAIN-SUFFIX,xiaov.uno,DIRECT',
  'DOMAIN-SUFFIX,sub.czrk168.top,兜底分流',
  'DOMAIN-SUFFIX,anxia.com,DIRECT',
  'DOMAIN-SUFFIX,gimy115.top,兜底分流',
  'DOMAIN,nyxen.org,兜底分流',
  'DOMAIN-SUFFIX,workingspaceshq.com,DIRECT',
  'DOMAIN-SUFFIX,linuxdo.org,DIRECT',
  'DOMAIN,hdhive.tgtodrive.top,兜底分流',
  'DOMAIN-SUFFIX,pay.lind0.cn,兜底分流',
  'DOMAIN,faka.embyhod.com,兜底分流',
  'IP-CIDR,103.212.187.44/32,DIRECT',
  'IP-CIDR,165.99.43.118/32,DIRECT',
  'IP-CIDR,50.7.158.194/32,日本',
  'IP-CIDR,123.51.231.132/32,台湾',
  'IP-CIDR,60.250.121.103/32,台湾',
  'DOMAIN-KEYWORD,astro,狮城',
  'DOMAIN-KEYWORD,wavve,狮城',
  'DOMAIN-SUFFIX,nodeseek.com,美国',
  'DOMAIN-KEYWORD,tracker,DIRECT',
  'DOMAIN-KEYWORD,v6tracker,DIRECT',
  'DOMAIN,oss2-china-south-bucket.selectgroup.click,DIRECT',
  'DOMAIN,oss1-china-alibaba-bucket.selectgroup.click,DIRECT',
  'DOMAIN-SUFFIX,oss-china-bucket.c1-click.selectgroup.click,DIRECT',
  'DOMAIN-KEYWORD,selectgroup,DIRECT',
  'DOMAIN-KEYWORD,oss-china-bucket,DIRECT',
  'DOMAIN-SUFFIX,subxiandan.top,兜底分流',
  'DOMAIN,api.xmancdn.net,DIRECT',
  'DOMAIN,api-huacloud.net,DIRECT',
  'DOMAIN-SUFFIX,api-flowercloud.com,DIRECT',
  'DOMAIN-SUFFIX,api-huacloud.com,DIRECT',
  'DOMAIN-SUFFIX,thetvdb.com,兜底分流',
  'DOMAIN-SUFFIX,cloudfront.net,DIRECT',
  'DOMAIN-SUFFIX,themoviedb.org,兜底分流',
  'DOMAIN-SUFFIX,lyzb33.pp,DIRECT',
  'DOMAIN-SUFFIX,lyzb.live,DIRECT',
  'DOMAIN-SUFFIX,lyzb3.app,DIRECT',
  'DOMAIN-SUFFIX,zb21sajhh83230-9939.app,DIRECT',
  'DOMAIN-SUFFIX,live07.workingspaceshq.com,DIRECT',
  'DOMAIN,iui.su,DIRECT',
  'DOMAIN,crhemby.mingri.site,DIRECT',
  'DOMAIN-SUFFIX,embyhod.com,DIRECT',
  'DOMAIN-SUFFIX,hdhive.com,兜底分流',
  'DOMAIN-SUFFIX,re0.me,兜底分流',
  'DOMAIN-SUFFIX,kelee.one,兜底分流',
  'DOMAIN-SUFFIX,steamserver.net,DIRECT',
  'DOMAIN-SUFFIX,jable.tv,兜底分流',
  'DOMAIN-KEYWORD,iturrit,Telegram',
  'DOMAIN,emby.jingzhe.pro,DIRECT',
  'DOMAIN,duangks.com,兜底分流',
  'DOMAIN-SUFFIX,seagmcdn.com,DIRECT',
  'DOMAIN-SUFFIX,seagm.com,DIRECT',
  'DOMAIN-SUFFIX,mobaibox.com,DIRECT',
  'IP-CIDR,183.207.0.0/16,DIRECT,no-resolve',
  'DOMAIN-SUFFIX,cctv.cn,DIRECT',
  'DOMAIN-SUFFIX,yangshipin.cn,DIRECT',
  'DOMAIN-SUFFIX,dnsany.com,DIRECT',
  'DOMAIN-SUFFIX,cmvideo.cn,DIRECT',
  'DOMAIN-SUFFIX,chinamobile.com,DIRECT',
  'DOMAIN-SUFFIX,cdn.hinet.net,台湾',
  'DOMAIN-SUFFIX,ofissaifreepc.akamaized.net,台湾',
  'DOMAIN-SUFFIX,ntd-tgc.cdn.hinet.netinet.net,台湾',
  'DOMAIN-SUFFIX,4gtvfree-cds.cdn.hinet.net,台湾',
  'DOMAIN-SUFFIX,4gtvfree-mozai.4gtv.tv,台湾',
  'DOMAIN-SUFFIX,4gtvfreepc-cds.cdn.hinet.net,台湾',
  'DOMAIN-SUFFIX,ntd-tgc.cdn.hinet.net,台湾',
  'DOMAIN-SUFFIX,smart.pendy.dpdns.org,美国',
  'DOMAIN-SUFFIX,sport.pendy.dpdns.org,美国',
  'DOMAIN-SUFFIX,docker.livednow.dpdns.org,美国',
  'DOMAIN-SUFFIX,pendy.dpdns.org,台湾',
  'DOMAIN-SUFFIX,4gtv.tv,香港',
  'DOMAIN-SUFFIX,hinet.net,香港',
  'DOMAIN-SUFFIX,ofiii.com,香港',
  'IP-CIDR,95.161.76.100/31,REJECT-DROP,no-resolve',
  'DOMAIN-KEYWORD,ugreen,DIRECT',
  'DOMAIN-SUFFIX,cn.bing.com,DIRECT',
  'DOMAIN-SUFFIX,pay.nft520.cn,兜底分流',
  'DOMAIN,ad.12306.cn,DIRECT',
  'DOMAIN,sdkapp.uve.weibo.com,DIRECT',
  'IP-CIDR,180.76.76.200/32,REJECT',
  'DOMAIN-REGEX,\\.log\\.,REJECT',
];

function main(config) {
  if (!config || typeof config !== 'object') {
    return config;
  }

  if (!Array.isArray(config.rules)) {
    config.rules = [];
  }

  // 自定义规则置于机场原规则之前
  config.rules = [
    ...customRules,
    ...config.rules,
  ];

  return config;
}
